
services:

  opensearch:
    image: opensearchproject/opensearch:2.19.1
    container_name: opensearch

    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g
      - DISABLE_SECURITY_PLUGIN=true
      - path.repo=/usr/share/opensearch/snapshots

    ulimits:
      memlock:
        soft: -1
        hard: -1

    volumes:
      - opensearch-data:/usr/share/opensearch/data
      - /home/ubuntu/opensearch-snapshots:/usr/share/opensearch/snapshots
      
    ports:
      - "9200:9200"
      - "9600:9600"

    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:9200 >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10

    restart: unless-stopped

    mem_limit: 4g

    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "5"

    networks:
      - vulnerability-network


  dashboards:
    image: opensearchproject/opensearch-dashboards:2.19.1
    container_name: dashboards

    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"

    ports:
      - "5601:5601"

    depends_on:
      opensearch:
        condition: service_healthy

    restart: unless-stopped

    mem_limit: 1g

    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "5"

    networks:
      - vulnerability-network


  fastapi:
    image: ghcr.io/raw-02/univulner-fastapi:latest
    pull_policy: always

    container_name: fastapi

    init: true

    env_file:
      - .env

    ports:
      - "8000:8000"

    depends_on:
      opensearch:
        condition: service_healthy

    restart: unless-stopped

    mem_limit: 1g

    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "5"

    networks:
      - vulnerability-network

  scheduler:
    image: ghcr.io/raw-02/univulner-scheduler:latest
    pull_policy: always
    
    container_name: scheduler

    env_file:
      - .env

    depends_on:
      opensearch:
        condition: service_healthy

    restart: unless-stopped

    networks:
      - vulnerability-network


volumes:
  opensearch-data:


networks:
  vulnerability-network:
    driver: bridge