name: UniVulner CD Pipeline

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io \
          -u "${{ secrets.GHCR_USERNAME }}" \
          --password-stdin

      - name: Build FastAPI Image
        run: |
          docker build \
          -f Docker/Dockerfile.fastapi \
          -t ghcr.io/${{ secrets.ORG_NAME }}/univulner-fastapi:latest \
          .

      - name: Build Scheduler Image
        run: |
          docker build \
          -f Docker/Dockerfile.scheduler \
          -t ghcr.io/${{ secrets.ORG_NAME }}/univulner-scheduler:latest \
          .

      - name: Push Images
        run: |
          docker push ghcr.io/${{ secrets.ORG_NAME }}/univulner-fastapi:latest
          docker push ghcr.io/${{ secrets.ORG_NAME }}/univulner-scheduler:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/Aggregator-Pipeline

            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io \
              -u "${{ secrets.GHCR_USERNAME }}" \
              --password-stdin

            docker compose pull

            docker compose up -d --remove-orphans

            docker image prune -f

            docker ps

      - name: Wait for FastAPI
        run: |
          for i in {1..12}; do
            if curl -fsS "${{ secrets.APP_URL }}/openapi.json" > /dev/null; then
              echo "Application is ready"
              exit 0
            fi
            echo "Waiting..."
            sleep 5
          done
          echo "Application did not become ready"
          exit 1


      - name: Pull OWASP ZAP Image
        run: docker pull ghcr.io/zaproxy/zaproxy:stable

      - name: Run OWASP ZAP Baseline Scan
        continue-on-error: true
        run: |
          mkdir -p reports
      
          chmod -R 777 reports

          docker run --rm \
            --user root \
            -v "${{ github.workspace }}/reports:/zap/wrk" \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-api-scan.py \
            -t "${{ secrets.APP_URL }}/openapi.json" \
            -f openapi \
            -J report.json \
            -r report.html

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Parse ZAP Report
        if: always() && hashFiles('reports/report.json') != ''
        run: python dast/zap_parser.py

      - name: Upload ZAP Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: reports/
